project:
  type: website

website:
  title: "MBS Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Data Engineering Methodology

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



